from contants import ModelType

lang_dict = {
    "english_cleaners": ["en"],
    "english_cleaners2": ["en"],
    "japanese_cleaners": ["ja"],
    "japanese_cleaners2": ["ja"],
    "korean_cleaners": ["ko"],
    "chinese_cleaners": ["zh"],
    "zh_ja_mixture_cleaners": ["zh", "ja"],
    "sanskrit_cleaners": ["sa"],
    "cjks_cleaners": ["zh", "ja", "ko", "sa"],
    "cjke_cleaners": ["zh", "ja", "ko", "en"],
    "cjke_cleaners2": ["zh", "ja", "ko", "en"],
    "cje_cleaners": ["zh", "ja", "en"],
    "cje_cleaners2": ["zh", "ja", "en"],
    "thai_cleaners": ["th"],
    "shanghainese_cleaners": ["sh"],
    "chinese_dialect_cleaners": ["zh", "ja", "sh", "gd", "en", "SZ", "WX", "CZ", "HZ", "SX", "NB", "JJ", "YX", "JD",
                                 "ZR", "PH", "TX", "JS", "HN", "LP", "XS", "FY", "RA", "CX", "SM", "TT", "WZ", "SC",
                                 "YB"],
    "bert_chinese_cleaners": ["zh"],
    ModelType.BERT_VITS2.value: ["zh", "ja"],
    f"{ModelType.BERT_VITS2.value}_v1.0": ["zh"],
    f"{ModelType.BERT_VITS2.value}_v1.0.0": ["zh"],
    f"{ModelType.BERT_VITS2.value}_v1.0.1": ["zh"],
    f"{ModelType.BERT_VITS2.value}_v1.1": ["zh", "ja"],
    f"{ModelType.BERT_VITS2.value}_v1.1.0": ["zh", "ja"],
    f"{ModelType.BERT_VITS2.value}_v1.1.0-transition": ["zh", "ja"],
    f"{ModelType.BERT_VITS2.value}_v1.1.1": ["zh", "ja"],
}
